apiVersion: batch/v1
kind: Job
metadata:
  name: hello-tmp
spec:
  template:
    metadata:
      name: hello-tmp
    spec:
      activeDeadlineSeconds: 100
      containers:
      - name: hello-tmp
        image: hello:local
        args: ["app"]
        env:
        - name: ENV_TYPE
          value: prod
        ports:
        - containerPort: 50000
      restartPolicy: Never





