apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello
  strategy: {}
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - image: hello
        name: hello
        ports:
        - containerPort: 8001
        volumeMounts:
        - mountPath: /app
          name: app-volume
        - mountPath: /usr/local/src/libutils
          name: libutils-volume
      # Host Volumes
      volumes:
      - name: app-volume
        hostPath:
          path: /Users/.minikube-mounts/hello/app
      - name: libutils-volume
        hostPath:
          path: /Users/.minikube-mounts/hello/libutils

        resources: {}
status: {}
