#
# Circle CI 2.0 Docs
# 
# For info, see: https://circleci.com/docs/2.0/
#

version: 2
jobs:
  build:
    docker:
      - image: newtonsystems/tools-docker-grpc-tools:0.2.1
    environment:
      DOCKER_PROJECT_NAME: hello
      TEST_REPORTS: /tmp/test-reports
      COVERALLS_REPO_TOKEN: 8hXhaqC0aBuwUKkPUcoB2VRmehTsP4Mz1
      CODECLIMATE_REPO_TOKEN: d25f67d317327459d14dca522099c332c71ecaa6344cef14b04445bbf4686e9c
    working_directory: ~/hello
    steps:
      - checkout
      - setup_remote_docker

      # Install Python py.test tools. (TODO: Skip install if already in cache.)
      - run:
          name: Install python requirements for deploy docs
          command: |
            pip install sphinx
            pip install sphinx_rtd_theme
            pip install sphinx_git

      - run:
          name: Clone dev-utils repo (Development utility scripts/tools)
          command: |
            cd ~/
            git clone -b $CIRCLE_BRANCH https://github.com/newtonsystems/dev-utils.git

      - run:
          name: Clone devops repo (Update the submodule to the latest change)
          command: |
            cd ~/
            git clone -b $CIRCLE_BRANCH https://github.com/newtonsystems/devops.git
            cd devops
            git submodule sync
            git submodule update --init
            git submodule foreach git pull origin $CIRCLE_BRANCH

      - run:
          name: Run Regression Tests
          command: |
            # Can't run make check FORCE_IGNORE_PREQ_TEST=true (docker volumes not supported)
            make circleci-check CODECLIMATE_REPO_TOKEN=${CODECLIMATE_REPO_TOKEN} FORCE_IGNORE_PREQ_TEST=true

      - run:
          name: Build & Push to Docker Hub (branch and latest (sync'd to master)) 
          command: |
            docker build -t newtonsystems/$DOCKER_PROJECT_NAME:$CIRCLE_BRANCH .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push newtonsystems/$DOCKER_PROJECT_NAME:$CIRCLE_BRANCH
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker tag newtonsystems/$DOCKER_PROJECT_NAME:$CIRCLE_BRANCH newtonsystems/$DOCKER_PROJECT_NAME:latest
                docker push newtonsystems/$DOCKER_PROJECT_NAME:latest
            fi

      - deploy:
          name: Upload coverage results to coveralls from within docker
          command: |
            docker run -e "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}" hello:local coveralls
 
      - deploy:
          name: Deploy python package to devpi 
          command: |
              # NOTE: At the moment even no changes are packaged up into
              #       a new python devpi package
              ~/devops/scripts/circle-upload-devpi.sh

      - deploy:
          name: Make and deploy sphinx documentation (after deployment of devpi - as changed version)
          command: |
              # NOTE: At the moment even no changes are packaged up into
              #       a new python devpi package
              pushd docs; make html ; popd
              ~/dev-utils/bin/deploy_sphinx_docs.sh $CIRCLE_PROJECT_REPONAME docs/build/html/

      # Upload test results
      - store_test_results:
          path: /tmp/test-reports
