
apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello
  name: hello
spec:
  ports:
  - name: grpc
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    run: hello
  type: NodePort
